# Generated by Django 4.1 on 2022-09-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
