# Generated by Django 4.1 on 2022-09-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_signed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='signed',
            new_name='active',
        ),
    ]
