# Generated by Django 4.1 on 2022-09-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='active',
        ),
        migrations.RemoveField(
            model_name='status',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='status',
            name='event',
        ),
        migrations.AddField(
            model_name='status',
            name='label',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
