# Generated by Django 4.1 on 2022-09-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_remove_status_active_remove_status_contract_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'status'},
        ),
    ]
