# Generated by Django 4.1 on 2022-09-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_amount_contract_payment_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
        migrations.AddField(
            model_name='contract',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
