# Generated by Django 4.1 on 2022-09-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_remove_contract_active_contract_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
