# Generated by Django 4.1 on 2022-09-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contract_payment_due'),
        ('events', '0005_alter_event_status_alter_event_support_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_contract', to='contracts.contract'),
            preserve_default=False,
        ),
    ]
